### ISSUE TITLE
Support saved searches in inliner script

### ISSUE THREAD

**Issue by drewdaemon** [elastic/visualizations_integrations_tools#2]
As of https://github.com/elastic/kibana/issues/148995 saved searches can now be added to a dashboard "by-value."

Because of this, https://github.com/elastic/package-spec/pull/635 started including saved searches in package spec by-reference warnings.

We should update the inline script to support saved searches.

**Comment by shmsr** [comment]
@drewdaemon Any update on this?

**Comment by drewdaemon** [comment]
@shmsr no one on the team has found time to complete this task yet. It's still on the radar. If your team has a deadline/goal we should be aware of, feel free to reach out with details!

**Comment by drewdaemon** [comment]
PR started: https://github.com/elastic/visualizations_integrations_tools/pull/3

**Comment by shmsr** [comment]
Thanks @drewdaemon for starting work on this 🎉

**Comment by drewdaemon** [comment]
Done in https://github.com/elastic/visualizations_integrations_tools/pull/3
